---
system: 'RP'
dt: 0.02              # 1.0 smallest time-step; smallest duration between 2 data points
n_periods: 6          # duration > n_periods * period_min (see below)
k_min: 5              # minimum exponent for multiplier of dt (e.g. time-step = dt * 2^k) 
k_max: 6              # maximum exponent for multiplier of dt (e.g. time-step = dt * 2^k) 
model_steps: 7        # (odd preferred) number of prediction steps during training; also determines the slice-size to chop the data-duration
#--------------------
abs_tol: 1.0e-8
rel_tol: 1.0e-8
#--------------------
n_wave: 10          # number of pressure waves generated
period_min: 10        # shortest period of any pressure wave (should be 10 or greater) 
period_max: 20       # longest period of any pressure wave (should be 10 or greater) 
amp_min: 1.4         # largest supremum of superposition of amplitudes |Cp(t)|
amp_max: 1.5          # smallest supremum of superposition of amplitudes |Cp(t)|
R_init: 1.0           # initial bubble radius (normalized)
Rdot_init: 0.0        # initial radial velocity
#-------------------
n_train: 128          # number of training samples (before slicing into sub-intervals)
n_val: 64             # number of validation samples (before slicing into sub-intervals)
n_test: 128           # number of testing samples (before slicing into sub-intervals)
n_layer: 3           # number of hidden layers
n_neuron: 128        # number of neurons per hidden layer
n_input: 4           # ResNet inputs: (R, Rdot, P, Pdot)
n_output: 2          # ResNet outputs: (R, Rdot)
n_epochs: 100000      # number of training epochs per learning rate
batch_fraction: 0.1   # batch size = fraction of validation samples post processing (e.g. 0.1 = 10%)
learn_rate_min: 1.0e-4
learn_rate_max: 1.0e-3
n_lr: 2
#-------------------
n_rungs: 8            # number of rungs on ladder between two critical points of Radius
steep_Rdot: 3         # steepness threshold for Rdot, which signals a sharp cusp
#-------------------
viscosity_dynamic: 0.0  # 1.0e-3  # (Pa*s) dynamic viscosity of liquid ; 8.63e-4
R_eq: 100.0e-6          # (m) equilibrium radius of bubble a.k.a. R_eq  ; 50.0e-6
P_eq: 1.0e+5            # 1.0e+5 ; (Pa) ambient pressure outside bubble ; 3.0e4
P_vap: 2.3e+3           # (Pa) vapor pressure inside bubble ; 3.538e+3 
poly_index: 1.4         #
surface_tension: 7.17875e-2  # (N/m) surface tension ; 7.17875e-2
density: 1.0e+3         # (kg/m^3) liquid density ; 9.98e2
#--------------------
plot_x_dim: 30
plot_y_dim: 10
title_fontsize: 40
legend_fontsize: 30
x_label_fontsize: 30
y_label_fontsize: 30
axis_fontsize: 30
box_fontsize: 30
line_width: 2